hook_func.bluealsa_load {
    lib "libasound_module_conf_bluealsa.so"
    func "bluealsa_conf_hook_load"
}

# load bluealsa dynamic configuration
@hooks [
	{
		func "bluealsa_load"
		errors true
	}
]


