/*
 * BlueALSA - io-worker-output.c
 * SPDX-FileCopyrightText: 2016-2026 BlueALSA developers
 * SPDX-License-Identifier: MIT
 */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "aplay-config.h"
#include "io-worker.h"
#include "io-worker-output.h"
#include "resampler.h"
#include "shared/defs.h"
#include "shared/log.h"

struct io_worker;

/* Intervals in seconds between consecutive PCM open retry attempts. */
static const unsigned int pcm_open_retry_intervals[] = { 1, 1, 2, 3, 5 };

bool io_worker_output_init(
				io_worker_output_t *output,
				snd_pcm_format_t input_format,
				unsigned int channels,
				unsigned int input_rate) {

	alsa_pcm_init(&output->pcm);
	output->pcm_open_retry_pcm_samples = 0;
	output->pcm_open_retries = 0;
	output->format_1 = input_format;
	output->format_2 = SND_PCM_FORMAT_UNKNOWN;
	output->channels = channels;
	output->in_rate = input_rate;
	output->pcm_flags = 0;
	output->use_resampler = false;

#if WITH_LIBSAMPLERATE
	memset(&output->resampler, 0, sizeof(output->resampler));
	/* The resampler requires the native endian format for the input data. */
	output->resampler_format = resampler_native_endian_format(input_format);
	memset(&output->resampled_buffer, 0, sizeof(output->resampled_buffer));

	output->alsa_pcm_started = false;

	if (config.resampler_method != RESAMPLER_CONV_NONE) {
		if (!resampler_is_input_format_supported(input_format))
			warn("Resampler not enabled: Unsupported input format: %s",
					snd_pcm_format_name(input_format));
		else {
			output->use_resampler = true;
			/* Disable alsa-lib resampling because our internal resampler can
			 * convert to a rate natively supported by the sound card. Initially
			 * also disable alsa-lib format conversion to try to use a format
			 * generated by the resampler. If that fails, then enable alsa-lib
			 * format conversion and have the resampler output its preferred
			 * FLOAT format. In this way the number of format conversions in the
			 * processing chain is minimized. */
			output->pcm_flags = SND_PCM_NO_AUTO_RESAMPLE | SND_PCM_NO_AUTO_FORMAT;
			/* The resampler uses FLOAT internally, so prefer that if the ALSA
			 * device supports it, to avoid the need to convert. Otherwise, use
			 * the resampler native endian integer format - input format. */
			output->format_1 = resampler_preferred_output_format();
			output->format_2 = output->resampler_format;
		}
	}
#endif
	return true;
}

void io_worker_output_close(io_worker_output_t *output) {
	debug("Closing ALSA playback PCM");
	alsa_pcm_close(&output->pcm);
#if WITH_LIBSAMPLERATE
	resampler_free(&output->resampler);
	ffb_free(&output->resampled_buffer);
	memset(&output->resampled_buffer, 0, sizeof(output->resampled_buffer));
#endif
}

bool io_worker_output_open(io_worker_output_t *output,
					ffb_t *input_buffer, size_t read_samples) {

	if (output->pcm_open_retries > 0) {
		/* After PCM open failure wait some time before retry. This can not be
		 * done with a sleep() call, because we have to drain PCM FIFO, so it
		 * will not have any stale data. */
		unsigned int interval = output->pcm_open_retries > ARRAYSIZE(pcm_open_retry_intervals) ?
			pcm_open_retry_intervals[ARRAYSIZE(pcm_open_retry_intervals) - 1] :
			pcm_open_retry_intervals[output->pcm_open_retries - 1];
		if ((output->pcm_open_retry_pcm_samples += read_samples) <= interval * output->in_rate * output->channels)
			return errno = EAGAIN, false;
	}

	debug("Opening ALSA playback PCM: name=%s channels=%u rate%s=%u",
			config.pcm_device, output->channels,
			output->pcm_flags & SND_PCM_NO_AUTO_RESAMPLE ? "~" : "",
			output->in_rate);

	char *tmp = NULL;
	int res = alsa_pcm_open(&output->pcm, config.pcm_device,
						output->format_1, output->format_2,	output->channels,
						output->in_rate, config.pcm_buffer_time,
						config.pcm_period_time, output->pcm_flags, &tmp);
	switch (res) {
	case 0:
		break;
	case -EINVAL:
#if WITH_LIBSAMPLERATE
		/* If the PCM failed to open because the sound card does not
		 * natively support either the float or integer formats of the
		 * resampler, then try again but this time with alsa-lib format
		 * conversion enabled. */
		if (output->use_resampler && output->pcm.format == SND_PCM_FORMAT_UNKNOWN) {
			free(tmp);
			if (alsa_pcm_open(&output->pcm, config.pcm_device, output->format_1,
						output->format_2, output->channels, output->in_rate,
						config.pcm_buffer_time, config.pcm_period_time,
						output->pcm_flags & ~SND_PCM_NO_AUTO_FORMAT, &tmp) == 0) {
				break;
			}
		}
#endif
		/* fall-through */
	default:
		warn("Couldn't open ALSA playback PCM: %s", tmp);
		output->pcm_open_retry_pcm_samples = 0;
		output->pcm_open_retries++;
		free(tmp);
		return errno = -res, false;
	}

	/* Resize the input buffer to ensure it is not less than the
	 * ALSA start threshold. This is to ensure that the PCM re-starts
	 * quickly after an overrun. */
	if (output->pcm.start_threshold > input_buffer->nmemb / output->channels)
		ffb_init(input_buffer, output->pcm.start_threshold * output->channels,
						input_buffer->size);

	output->write_buffer = input_buffer;

#if WITH_LIBSAMPLERATE
	if (output->use_resampler) {

		/* Initialize the resampler which will try to keep the playback delay
		 * within configured limits. The lower and upper limits are set to
		 * the ALSA start threshold and the start threshold plus the period
		 * size respectively. The resampler will adapt the rate to keep the
		 * delay within these limits. */
		if ((res = resampler_init(
						&output->resampler,
						config.resampler_method,
						output->channels,
						output->resampler_format,
						output->in_rate,
						output->pcm.format,
						output->pcm.rate,
						output->pcm.start_threshold,
						output->pcm.start_threshold + output->pcm.period_frames)) == -1) {
			error("Couldn't initialize resampler: %s", strerror(errno));
			return false;
		}

#if DEBUG
		if (config.verbose >= 4)
			debug("PCM sample rate conversion: %u Hz -> %#.2f Hz", output->in_rate,
					output->in_rate * resampler_current_rate_ratio(&output->resampler));
#endif

		/* The resampler output buffer is sized to accommodate the
		 * result of resampling a full read_buffer, plus a little extra
		 * to allow for positive adaptive resampling adjustment. */
		size_t buffer_size = input_buffer->nmemb * output->pcm.rate / output->in_rate;
		buffer_size = (buffer_size * 110) / 100;
		ffb_init(&output->resampled_buffer, buffer_size, snd_pcm_format_size(output->pcm.format, 1));
		output->write_buffer = &output->resampled_buffer;

	}
#endif

	/* Reset retry counters. */
	output->pcm_open_retry_pcm_samples = 0;
	output->pcm_open_retries = 0;

	return true;
}

int io_worker_output_write(io_worker_output_t *output,
					ffb_t *input_buffer,
					bool mute,
					bool drain) {

	/* Here we use errno to distinguish whether a return value of -1 indicates
	 * failure or simply a infinite timeout; so we initialize it to zero. */
	errno = 0;

	if (mute) {
		snd_pcm_format_t format = output->pcm.format;
#if WITH_LIBSAMPLERATE
		if (output->use_resampler)
			format = output->resampler_format;
#endif
		snd_pcm_format_set_silence(format, input_buffer->data, ffb_len_out(input_buffer));
	}

#if WITH_LIBSAMPLERATE
	if (output->use_resampler &&
			resampler_process(&output->resampler, input_buffer, &output->resampled_buffer) != 0)
		return -1;
#endif

	if (alsa_pcm_write(&output->pcm, output->write_buffer, drain) < 0)
		return -1;

	/* Set the poll() timeout such that this thread is always woken before
	 * an ALSA underrun can occur. */
	int timeout;
	if (alsa_pcm_is_running(&output->pcm)) {
		timeout = 1000 * output->pcm.hw_avail / output->pcm.rate;
		/* poll() timeouts may be late because of the kernel scheduler and
		 * workload, and there may be additional processing delays before
		 * we can write to the ALSA PCM again. So we allow for this by setting
		 * the timeout value 5ms before the underrun deadline. */
		if ((timeout -= 5) < 0)
			timeout = 0;
	}
	else {
		/* When the ALSA PCM has not yet started then we request an infinite
		 * timeout. To distinguish this from a failed write we use EAGAIN. */
		errno = EAGAIN;
		timeout = -1;
	}
	return timeout;

}

snd_pcm_uframes_t io_worker_output_delay(
		const io_worker_output_t *output) {

	snd_pcm_uframes_t delay = output->pcm.delay;

#if WITH_LIBSAMPLERATE
	if (output->use_resampler) {
		/* Add the delay accumulated in the resampler. */
		delay += ffb_len_out(&output->resampled_buffer) / output->channels;
		/* Convert the output rate to the BlueALSA PCM sample rate. */
		delay /= resampler_current_rate_ratio(&output->resampler);
	}
#endif

	return delay;
}

#if WITH_LIBSAMPLERATE
void io_worker_output_update_rate(io_worker_output_t *output,
					size_t frames_read, size_t delay) {
	if (output->use_resampler) {
		bool rate_changed = false;
		if (output->pcm.underrun) {
			debug("Resetting resampler");
			resampler_reset(&output->resampler);
			rate_changed = true;
		}
		if (!alsa_pcm_is_running(&output->pcm))
			output->alsa_pcm_started = false;
		else {
			if (!output->alsa_pcm_started) {
				/* The ALSA start threshold has been reached, so reset the
				 * resampler to initialize adaptive resampling. */
				resampler_reset(&output->resampler);
				output->alsa_pcm_started = true;
			}
			rate_changed = resampler_update_rate_ratio(&output->resampler,
					frames_read, delay);
		}

		if (config.verbose >= 4 && rate_changed)
			debug("PCM sample rate conversion: %u Hz -> %#.2f Hz", output->in_rate,
					output->in_rate * resampler_current_rate_ratio(&output->resampler));
	}
}
#else
void io_worker_output_update_rate(io_worker_output_t *output,
					size_t frames_read, size_t delay) {
	(void) output;
	(void) frames_read;
	(void) delay;
}
#endif
